development:
  adapter: redis
  url: redis://:boodog@redis-17737.c12.us-east-1-4.ec2.cloud.redislabs.com:17737

test:
  adapter: async

production:
  adapter: redis
  url: redis://:boodog@redis-17737.c12.us-east-1-4.ec2.cloud.redislabs.com:17737
